# Generated by Django 5.2.1 on 2025-05-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('center_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='center_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail', to='center_details.centerdetail'),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
