# Generated by Django 5.2.1 on 2025-05-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_staffaccount_center_name_and_more'),
        ('center_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffaccount',
            name='center_name',
        ),
        migrations.AddField(
            model_name='staffaccount',
            name='center_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_detail', to='center_details.centerdetail'),
        ),
    ]
