# Generated by Django 5.2.1 on 2025-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_staffaccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If true, the user is locked out and cannot log in.'),
        ),
    ]
