# Generated by Django 5.2.1 on 2025-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_staffaccount_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffaccount',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
