# Generated by Django 5.2.1 on 2025-09-22 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_staffaccount_failed_login_attempts_and_more'),
        ('center_detail', '0011_alter_subscription_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffaccount',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='center_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts', to='center_detail.centerdetail'),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates that this user can log into the admin site.', verbose_name='admin status'),
        ),
    ]
