# Generated by Django 5.2.1 on 2025-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_staffaccount_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffaccount',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='lockout_until',
        ),
        migrations.AddField(
            model_name='staffaccount',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Required by Django admin. Automatically synced with "admin status".', verbose_name='staff status'),
        ),
    ]
