# Generated by Django 5.2.12 on 2026-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_staffaccount_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='_has_accepted_license',
            field=models.BooleanField(default=False, help_text='If true, the user has accepted the license agreement.'),
        ),
    ]
