# Generated by Django 5.2.12 on 2026-05-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_staffaccount__has_accepted_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffaccount',
            old_name='_has_accepted_license',
            new_name='has_accepted_license',
        ),
    ]
