# Generated by Django 5.2.1 on 2025-12-22 07:40

import diagnosis.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center_detail', '0011_alter_subscription_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_franchise_lab', models.BooleanField(default=False, help_text='If True, bills with this category require franchise name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnosis Category',
                'verbose_name_plural': 'Diagnosis Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(editable=False, max_length=22, unique=True)),
                ('date_of_test', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_age', models.PositiveIntegerField(validators=[diagnosis.models.validate_age])),
                ('patient_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('patient_phone_number', models.PositiveBigIntegerField(default=9999999999, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10 and 15 digits.', regex='^\\d{10,15}$')])),
                ('date_of_bill', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill_status', models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Fully Paid', max_length=15)),
                ('total_amount', models.IntegerField(editable=False)),
                ('paid_amount', models.IntegerField(blank=True, default=0)),
                ('disc_by_center', models.IntegerField(default=0)),
                ('disc_by_doctor', models.IntegerField(default=0)),
                ('incentive_amount', models.IntegerField(default=0, editable=False)),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_bill', to='center_detail.centerdetail')),
                ('test_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_done_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_types', to='diagnosis.diagnosiscategory')),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_diagnosis', to='center_detail.centerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='BillDiagnosisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_time', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_diagnosis_types', to='diagnosis.bill')),
                ('diagnosis_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_references', to='diagnosis.diagnosistype')),
            ],
            options={
                'unique_together': {('bill', 'diagnosis_type')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='diagnosis_types',
            field=models.ManyToManyField(related_name='bills', through='diagnosis.BillDiagnosisType', to='diagnosis.diagnosistype'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('hospital_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Please enter a valid phone number.', regex='^\\+?[0-9]{1,15}$')])),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('ultrasound_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('pathology_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('ecg_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('xray_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('franchise_lab_percentage', models.PositiveIntegerField(default=30, validators=[diagnosis.models.validate_incentive_percentage])),
                ('others_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail', to='center_detail.centerdetail')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='referred_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_patients_by_doctor', to='diagnosis.doctor'),
        ),
        migrations.CreateModel(
            name='FranchiseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Please enter a valid phone number.', regex='^\\+?[0-9]{1,15}$')])),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_franchise', to='center_detail.centerdetail')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='franchise_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.franchisename'),
        ),
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to=diagnosis.models.report_file_upload_path)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnosis.bill')),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_report', to='center_detail.centerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCategoryPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_percentages', to='diagnosis.diagnosiscategory')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_percentages', to='diagnosis.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Category Percentage',
                'verbose_name_plural': 'Doctor Category Percentages',
                'unique_together': {('doctor', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SampleTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('X-Ray', 'X-Ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Franchise Lab', 'Franchise Lab'), ('Others', 'Others')], max_length=50, null=True)),
                ('diagnosis_name', models.CharField(max_length=255)),
                ('sample_report_file', models.FileField(upload_to=diagnosis.models.sample_report_file_upload_path)),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_sample_test_report', to='center_detail.centerdetail')),
            ],
            options={
                'unique_together': {('category', 'diagnosis_name')},
            },
        ),
    ]
