# Generated by Django 5.2.1 on 2025-05-28 15:06

import diagnosis.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center_detail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('X-ray', 'X-ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('ultrasound_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('pathology_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('ecg_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('xray_percentage', models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage])),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail', to='center_detail.centerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_of_test', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_age', models.PositiveIntegerField(validators=[diagnosis.models.validate_age])),
                ('patient_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('date_of_bill', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill_status', models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disc_by_center', models.IntegerField(default=0)),
                ('disc_by_doctor', models.IntegerField(default=0)),
                ('incentive_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_bill', to='center_detail.centerdetail')),
                ('test_done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_done_by', to=settings.AUTH_USER_MODEL)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_type', to='diagnosis.diagnosistype')),
                ('referred_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_patients_by_doctor', to='diagnosis.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnosis.bill')),
            ],
        ),
    ]
