# Generated by Django 5.2.1 on 2025-05-29 03:45

import diagnosis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0001_initial'),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosistype',
            name='center_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_diagnosis', to='center_detail.centerdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='center_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_report', to='center_detail.centerdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(upload_to=diagnosis.models.report_file_upload_path),
        ),
    ]
