# Generated by Django 5.2.1 on 2025-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0001_initial'),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='PatientReport',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_status',
            field=models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Fully Paid', max_length=15),
        ),
    ]
