# Generated by Django 5.2.1 on 2025-12-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_alter_doctor_address_alter_doctor_ecg_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosistype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_types', to='diagnosis.diagnosiscategory'),
        ),
    ]
