# Generated by Django 5.2.1 on 2025-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diagnosistype_center_detail_report_center_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='test_type',
            new_name='diagnosis_type',
        ),
        migrations.AlterField(
            model_name='bill',
            name='incentive_amount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.IntegerField(editable=False),
        ),
    ]
