# Generated by Django 5.2.1 on 2025-05-31 16:20

import diagnosis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_rename_test_type_bill_diagnosis_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='franchise_lab_percentage',
            field=models.PositiveIntegerField(default=30, validators=[diagnosis.models.validate_incentive_percentage]),
        ),
    ]
