# Generated by Django 5.2.1 on 2026-04-04 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_alter_diagnosistype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='patient_phone_number',
            field=models.PositiveBigIntegerField(default=9999999999, validators=[django.core.validators.MinValueValidator(1000000000, message='Phone number must be at least 10 digits.'), django.core.validators.MaxValueValidator(999999999999999, message='Phone number must be at most 15 digits.')]),
        ),
    ]
