# Generated by Django 5.2.1 on 2025-06-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_sampletestreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletestreport',
            name='diagnosis_type',
            field=models.CharField(choices=[('X-ray', 'X-ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound')], max_length=50),
        ),
    ]
