# Generated by Django 5.2.1 on 2026-04-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0011_alter_subscription_center'),
        ('diagnosis', '0004_alter_bill_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosiscategory',
            name='center_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_categories', to='center_detail.centerdetail'),
        ),
        migrations.AlterField(
            model_name='diagnosiscategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
