# Generated by Django 5.2.1 on 2025-05-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_doctor_franchise_lab_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='diagnosis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_type', to='diagnosis.diagnosistype'),
        ),
    ]
