# Generated by Django 5.2.1 on 2025-05-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_alter_bill_diagnosis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosistype',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
