# Generated by Django 5.2.1 on 2025-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_alter_sampletestreport_diagnosis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosistype',
            name='category',
            field=models.CharField(choices=[('X-ray', 'X-ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Franchise Lab', 'Franchise Lab')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampletestreport',
            name='diagnosis_type',
            field=models.CharField(choices=[('X-ray', 'X-ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Franchise Lab', 'Franchise Lab')], max_length=50),
        ),
    ]
