# Generated by Django 5.2.1 on 2026-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0011_alter_subscription_center'),
        ('diagnosis', '0005_diagnosiscategory_center_detail_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diagnosiscategory',
            constraint=models.UniqueConstraint(fields=('name', 'center_detail'), name='unique_category_name_per_center'),
        ),
    ]
