# Generated by Django 5.2.1 on 2026-04-04 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_diagnosiscategory_unique_category_name_per_center'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diagnosiscategory',
            name='unique_category_name_per_center',
        ),
        migrations.RemoveField(
            model_name='diagnosiscategory',
            name='center_detail',
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient_phone_number',
            field=models.PositiveBigIntegerField(default=9999999999, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10 and 15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='diagnosiscategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
