# Generated by Django 5.2.1 on 2025-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_alter_diagnosistype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosistype',
            name='price',
            field=models.IntegerField(),
        ),
    ]
