# Generated by Django 5.2.1 on 2025-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_alter_diagnosistype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='franchise_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
