# Generated by Django 5.2.1 on 2025-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_alter_diagnosistype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(editable=False, max_length=22, unique=True),
        ),
    ]
