# Generated by Django 5.2.1 on 2025-06-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_bill_franchise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='franchise_name',
        ),
    ]
