# Generated by Django 5.2.12 on 2026-04-10 02:24

from django.db import migrations


def reset_postgres_pk_sequences(apps, schema_editor):
    """
    Reset PostgreSQL sequences so next INSERT uses MAX(id)+1.
    This fixes duplicate primary key errors after data imports/migrations.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    tables = [
        "diagnosis_diagnosiscategory",
        "diagnosis_doctor",
        "diagnosis_diagnosistype",
        "diagnosis_franchisename",
        "diagnosis_bill",
        "diagnosis_patientreport",
        "diagnosis_sampletestreport",
        "diagnosis_auditlog",
        "diagnosis_doctorcategorypercentage",
        "diagnosis_billdiagnosistype",
    ]

    with schema_editor.connection.cursor() as cursor:
        for table in tables:
            cursor.execute(
                f"""
                SELECT setval(
                    pg_get_serial_sequence('{table}', 'id'),
                    COALESCE((SELECT MAX(id) FROM {table}), 0) + 1,
                    false
                );
                """
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0008_auditlog'),
    ]

    operations = [
        migrations.RunPython(reset_postgres_pk_sequences, noop_reverse),
    ]
