# Generated by Django 5.2.1 on 2025-06-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0009_bill_franchise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(default='Chaurasiya Medical Agency', max_length=30),
            preserve_default=False,
        ),
    ]
