# Generated by Django 5.2.12 on 2026-05-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0025_alter_activesubscription_subscription_plan'),
        ('diagnosis', '0010_bill_message_tracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sampletestreport',
            unique_together={('center_detail', 'category', 'diagnosis_name')},
        ),
    ]
