# Generated by Django 5.2.1 on 2025-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0010_alter_bill_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], max_length=15),
        ),
    ]
