# Generated by Django 5.2.1 on 2025-06-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0011_alter_doctor_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(max_length=30),
        ),
    ]
