# Generated by Django 5.2.12 on 2026-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0011_alter_sampletestreport_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletestreport',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
            preserve_default=False,
        ),
    ]
