# Generated by Django 5.2.1 on 2025-06-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0011_alter_bill_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='referred_by_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referred_patients_by_doctor', to='diagnosis.doctor'),
            preserve_default=False,
        ),
    ]
