# Generated by Django 5.2.1 on 2025-06-18 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0012_alter_doctor_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Please enter a valid phone number with country code.', regex='^\\+[1-9]{1}[0-9]{3,14}$')]),
        ),
    ]
