# Generated by Django 5.2.1 on 2025-06-18 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0013_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Please enter a valid phone number.', regex='^\\+?[0-9]{1,15}$')]),
        ),
    ]
