# Generated by Django 5.2.1 on 2025-07-02 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0014_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_of_bill',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_of_test',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
