# Generated by Django 5.2.1 on 2025-07-02 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0015_alter_bill_date_of_bill_alter_bill_date_of_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_of_bill',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_of_test',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
