# Generated by Django 5.2.1 on 2025-08-06 08:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0001_initial'),
        ('diagnosis', '0016_alter_bill_date_of_bill_alter_bill_date_of_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Please enter a valid phone number.', regex='^\\+?[0-9]{1,15}$')])),
                ('center_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_detail_franchise', to='center_detail.centerdetail')),
            ],
        ),
    ]
