# Generated by Django 5.2.1 on 2025-08-06 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0017_franchisename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchisename',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Please enter a valid phone number.', regex='^\\+?[0-9]{1,15}$')]),
        ),
    ]
