# Generated by Django 5.2.1 on 2025-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0018_alter_franchisename_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
