# Generated by Django 5.2.1 on 2025-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0019_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosistype',
            name='category',
            field=models.CharField(choices=[('X-Ray', 'X-Ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Franchise Lab', 'Franchise Lab')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampletestreport',
            name='diagnosis_type',
            field=models.CharField(choices=[('X-Ray', 'X-Ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Franchise Lab', 'Franchise Lab')], max_length=50),
        ),
    ]
