# Generated by Django 5.2.1 on 2025-09-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0021_convert_franchise_char_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='franchise_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.franchisename'),
        ),
    ]
