# Generated by Django 5.2.1 on 2025-09-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0022_alter_bill_franchise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='referred_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_patients_by_doctor', to='diagnosis.doctor'),
        ),
    ]
