# Generated by Django 5.2.1 on 2025-09-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0023_alter_bill_referred_by_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='patient_phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
