# Generated by Django 5.2.1 on 2025-10-01 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0023_alter_bill_referred_by_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='patient_phone_number',
            field=models.PositiveBigIntegerField(default=9999999999, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10 and 15 digits.', regex='^\\d{10,15}$')]),
        ),
    ]
