# Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations

def update_phone_numbers(apps, schema_editor):
    """
    Finds all existing bills and sets their patient_phone_number to '0000000000'.
    """
    # Use apps.get_model to get the historical version of the Bill model
    Bill = apps.get_model('diagnosis', 'Bill')

    # Perform an efficient bulk update for all existing bills
    Bill.objects.all().update(patient_phone_number="0000000000")

def do_nothing(apps, schema_editor):
    # The reverse operation does nothing, as we can't restore old phone numbers.
    pass

class Migration(migrations.Migration):

    dependencies = [
        # This MUST point to the migration file created in Step 2.
        # Django automatically sets this dependency correctly.
        ('diagnosis', '0024_bill_patient_phone_number'),
    ]

    operations = [
        # This operation runs our custom Python function
        migrations.RunPython(update_phone_numbers, reverse_code=do_nothing),
    ]