# Generated by Django 5.2.1 on 2025-10-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0024_bill_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletestreport',
            name='diagnosis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_reports', to='diagnosis.diagnosistype'),
        ),
        migrations.AlterUniqueTogether(
            name='sampletestreport',
            unique_together={('diagnosis_type', 'diagnosis_name')},
        ),
    ]
