# Generated by Django 5.2.1 on 2025-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0025_alter_sampletestreport_diagnosis_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sampletestreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sampletestreport',
            name='category',
            field=models.CharField(choices=[('X-Ray', 'X-Ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Franchise Lab', 'Franchise Lab')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='sampletestreport',
            name='diagnosis_type',
        ),
    ]
