# Generated by Django 5.2.1 on 2025-10-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0026_alter_sampletestreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sampletestreport',
            unique_together={('category', 'diagnosis_name')},
        ),
    ]
