# Generated by Django 5.2.1 on 2025-12-21 18:11

import diagnosis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0027_alter_sampletestreport_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='diagnosis_type',
        ),
        migrations.AddField(
            model_name='doctor',
            name='others_percentage',
            field=models.PositiveIntegerField(default=50, validators=[diagnosis.models.validate_incentive_percentage]),
        ),
        migrations.AlterField(
            model_name='diagnosistype',
            name='category',
            field=models.CharField(choices=[('X-Ray', 'X-Ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Franchise Lab', 'Franchise Lab'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampletestreport',
            name='category',
            field=models.CharField(choices=[('X-Ray', 'X-Ray'), ('Pathology', 'Pathology'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Franchise Lab', 'Franchise Lab'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BillDiagnosisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_time', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_diagnosis_types', to='diagnosis.bill')),
                ('diagnosis_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_references', to='diagnosis.diagnosistype')),
            ],
            options={
                'unique_together': {('bill', 'diagnosis_type')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='diagnosis_types',
            field=models.ManyToManyField(related_name='bills', through='diagnosis.BillDiagnosisType', to='diagnosis.diagnosistype'),
        ),
    ]
