# Generated by Django 5.2.1 on 2025-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
