# Generated by Django 5.2.1 on 2025-08-31 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('valid_days', models.PositiveIntegerField(default=30)),
                ('valid_till', models.DateField(blank=True, editable=False, null=True)),
                ('days_left', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='center_detail.centerdetail')),
            ],
        ),
    ]
