# Generated by Django 5.2.1 on 2025-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0003_remove_subscription_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='days_left',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
