# Generated by Django 5.2.1 on 2025-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0004_remove_subscription_days_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
