# Generated by Django 5.2.1 on 2025-08-31 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0005_alter_subscription_valid_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='valid_days',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(default='2026-08-31'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='center_detail.centerdetail'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
