# Generated by Django 5.2.1 on 2025-08-31 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0008_alter_subscription_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='center_detail.centerdetail'),
        ),
    ]
