# Generated by Django 5.2.1 on 2026-04-08

from django.db import migrations, models
import django.db.models.deletion


def create_subscription_plan_table(apps, schema_editor):
    """Create SubscriptionPlan table."""
    # Use raw SQL to create the table
    schema_editor.execute("""
        CREATE TABLE IF NOT EXISTS center_detail_subscriptionplan (
            id bigint NOT NULL PRIMARY KEY,
            name varchar(100) UNIQUE NOT NULL,
            duration_days integer NOT NULL DEFAULT 30,
            price_monthly numeric(10, 2) NOT NULL DEFAULT 0,
            bulk_price numeric(10, 2) NOT NULL DEFAULT 0,
            monthly_sms_quota integer NOT NULL DEFAULT 0,
            bulk_sms_quota integer NOT NULL DEFAULT 0,
            is_custom boolean NOT NULL DEFAULT false,
            is_active boolean NOT NULL DEFAULT true
        )
    """)


class Migration(migrations.Migration):

    dependencies = [
        ("center_detail", "0011_alter_subscription_center"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("duration_days", models.PositiveIntegerField(default=30)),
                ("price_monthly", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("bulk_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("monthly_sms_quota", models.PositiveIntegerField(default=0)),
                ("bulk_sms_quota", models.PositiveIntegerField(default=0)),
                ("is_custom", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="subscription",
            name="duration_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="monthly_sms_quota",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscriptions", to="center_detail.subscriptionplan"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="price_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="bulk_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="bulk_sms_quota",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
