# Generated by Django 5.2.1 on 2026-04-08

from django.db import migrations, models
from datetime import date, timedelta


def seed_plans_and_link_subscriptions(apps, schema_editor):
    """Create default plans and link all center subscriptions to FREE plan."""
    # Normalize legacy column names from earlier migration attempt.
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'center_detail_subscriptionplan'
                  AND column_name = 'price_yearly'
            ) THEN
                ALTER TABLE center_detail_subscriptionplan
                RENAME COLUMN price_yearly TO bulk_price;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'center_detail_subscriptionplan'
                  AND column_name = 'yearly_sms_quota'
            ) THEN
                ALTER TABLE center_detail_subscriptionplan
                RENAME COLUMN yearly_sms_quota TO bulk_sms_quota;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'center_detail_subscription'
                  AND column_name = 'price_yearly'
            ) THEN
                ALTER TABLE center_detail_subscription
                RENAME COLUMN price_yearly TO bulk_price;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'center_detail_subscription'
                  AND column_name = 'yearly_sms_quota'
            ) THEN
                ALTER TABLE center_detail_subscription
                RENAME COLUMN yearly_sms_quota TO bulk_sms_quota;
            END IF;
        END $$;
        """
    )

    Subscription = apps.get_model("center_detail", "Subscription")
    SubscriptionPlan = apps.get_model("center_detail", "SubscriptionPlan")
    CenterDetail = apps.get_model("center_detail", "CenterDetail")

    # Delete all existing subscriptions
    Subscription.objects.all().delete()

    # Delete all existing plans
    SubscriptionPlan.objects.all().delete()

    # Create the three default plans
    free_plan = SubscriptionPlan.objects.create(
        name="FREE",
        duration_days=30,
        price_monthly=0,
        bulk_price=0,
        monthly_sms_quota=0,
        bulk_sms_quota=0,
        is_custom=False,
        is_active=True,
    )

    SubscriptionPlan.objects.create(
        name="BASIC",
        duration_days=30,
        price_monthly=0,
        bulk_price=0,
        monthly_sms_quota=0,
        bulk_sms_quota=0,
        is_custom=False,
        is_active=True,
    )

    SubscriptionPlan.objects.create(
        name="PREMIUM",
        duration_days=365,
        price_monthly=0,
        bulk_price=0,
        monthly_sms_quota=0,
        bulk_sms_quota=0,
        is_custom=False,
        is_active=True,
    )

    # Create subscription for each center linked to FREE plan
    today = date.today()
    for center in CenterDetail.objects.all():
        Subscription.objects.create(
            center=center,
            plan=free_plan,
            plan_type="FREE",
            name="FREE",
            duration_days=30,
            price_monthly=0,
            bulk_price=0,
            monthly_sms_quota=0,
            bulk_sms_quota=0,
            is_custom=False,
            purchase_date=today,
            expiry_date=today + timedelta(days=30),
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("center_detail", "0012_subscription_plan"),
    ]

    operations = [
        migrations.RunPython(seed_plans_and_link_subscriptions, migrations.RunPython.noop),
    ]
