# Generated by Django 5.2.1 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


def map_center_to_plan(apps, schema_editor):
    CenterDetail = apps.get_model("center_detail", "CenterDetail")
    Subscription = apps.get_model("center_detail", "Subscription")
    SubscriptionPlan = apps.get_model("center_detail", "SubscriptionPlan")

    free_plan, _ = SubscriptionPlan.objects.get_or_create(
        name="FREE",
        defaults={
            "duration_days": 30,
            "price_monthly": 0,
            "bulk_price": 0,
            "monthly_sms_quota": 0,
            "bulk_sms_quota": 0,
            "is_custom": False,
            "is_active": True,
        },
    )

    for center in CenterDetail.objects.all().iterator():
        sub = (
            Subscription.objects.filter(center_id=center.id)
            .order_by("-purchase_date", "-id")
            .first()
        )
        center.subscription_plan_id = sub.plan_id if sub and sub.plan_id else free_plan.id
        center.save(update_fields=["subscription_plan"])


class Migration(migrations.Migration):

    dependencies = [
        ("center_detail", "0013_seed_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="centerdetail",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="centers",
                to="center_detail.subscriptionplan",
            ),
        ),
        migrations.RunPython(map_center_to_plan, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
