# Generated by Django 5.2.1 on 2026-04-08

from datetime import date
from django.db import migrations, models


def backfill_plan_activation_date(apps, schema_editor):
    CenterDetail = apps.get_model("center_detail", "CenterDetail")

    CenterDetail.objects.filter(
        subscription_plan__isnull=False,
        plan_activated_on__isnull=True,
    ).update(plan_activated_on=date.today())


class Migration(migrations.Migration):

    dependencies = [
        ("center_detail", "0014_remove_subscription_keep_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="centerdetail",
            name="plan_activated_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_plan_activation_date, migrations.RunPython.noop),
    ]
