# Generated by Django 5.2.1 on 2026-04-08

from datetime import date, timedelta
from django.db import migrations, models


def backfill_center_status(apps, schema_editor):
    CenterDetail = apps.get_model("center_detail", "CenterDetail")
    for center in CenterDetail.objects.all().iterator():
        if not center.plan_activated_on or not center.subscription_plan_id:
            continue
        expiry_date = center.plan_activated_on + timedelta(days=center.subscription_plan.duration_days)
        center.is_active = expiry_date > date.today()
        center.save(update_fields=["is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ("center_detail", "0015_center_plan_activation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="centerdetail",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(backfill_center_status, migrations.RunPython.noop),
    ]
