# Generated by Django 5.2.12 on 2026-04-09 14:23

import django.db.models.deletion
from django.db import migrations, models


def seed_billing_options_and_assign_centers(apps, schema_editor):
    SubscriptionPlan = apps.get_model('center_detail', 'SubscriptionPlan')
    SubscriptionBillingOption = apps.get_model('center_detail', 'SubscriptionBillingOption')
    CenterDetail = apps.get_model('center_detail', 'CenterDetail')

    for plan in SubscriptionPlan.objects.all():
        monthly_quota = getattr(plan, 'monthly_sms_quota', 0) or 0
        bulk_quota = getattr(plan, 'bulk_sms_quota', 0) or 0
        current_period_quota = getattr(plan, 'sms_quota_per_period', 0) or 0

        if current_period_quota == 0:
            plan.sms_quota_per_period = monthly_quota if monthly_quota > 0 else bulk_quota

        if not getattr(plan, 'quota_period_unit', None):
            plan.quota_period_unit = 'MONTHLY'

        plan.save(
            update_fields=[
                'sms_quota_per_period',
                'quota_period_unit',
            ]
        )

        monthly_price = getattr(plan, 'price_monthly', 0) or 0
        bulk_price = getattr(plan, 'bulk_price', 0) or 0

        yearly_base_price = monthly_price * 12
        if yearly_base_price > 0 and bulk_price > 0 and bulk_price <= yearly_base_price:
            yearly_discount_percent = ((yearly_base_price - bulk_price) / yearly_base_price) * 100
        else:
            yearly_discount_percent = 0

        default_for_plan = 'Monthly'
        if getattr(plan, 'duration_days', 30) not in (30, 365):
            default_for_plan = f'Custom {plan.duration_days}d'

        SubscriptionBillingOption.objects.update_or_create(
            plan=plan,
            name='Monthly',
            defaults={
                'code': 'MONTHLY',
                'duration_days': 30,
                'base_price': monthly_price,
                'discount_percent': 0,
                'is_default': default_for_plan == 'Monthly',
                'is_active': True,
            },
        )

        SubscriptionBillingOption.objects.update_or_create(
            plan=plan,
            name='Yearly',
            defaults={
                'code': 'YEARLY',
                'duration_days': 365,
                'base_price': yearly_base_price,
                'discount_percent': yearly_discount_percent,
                'is_default': default_for_plan == 'Yearly',
                'is_active': True,
            },
        )

        if default_for_plan.startswith('Custom '):
            custom_price = bulk_price if bulk_price > 0 else monthly_price
            SubscriptionBillingOption.objects.update_or_create(
                plan=plan,
                name=default_for_plan,
                defaults={
                    'code': 'CUSTOM',
                    'duration_days': plan.duration_days,
                    'base_price': custom_price,
                    'discount_percent': 0,
                    'is_default': True,
                    'is_active': True,
                },
            )

    for center in CenterDetail.objects.select_related('subscription_plan').all():
        if not center.subscription_plan_id:
            free_plan = SubscriptionPlan.objects.filter(name='FREE').first()
            if free_plan:
                center.subscription_plan = free_plan

        if center.subscription_plan_id and not center.billing_option_id:
            option = SubscriptionBillingOption.objects.filter(
                plan_id=center.subscription_plan_id,
                is_active=True,
                is_default=True,
            ).order_by('id').first()
            if option is None:
                option = SubscriptionBillingOption.objects.filter(
                    plan_id=center.subscription_plan_id,
                    is_active=True,
                ).order_by('duration_days', 'id').first()
            center.billing_option = option

        center.save(update_fields=['subscription_plan', 'billing_option'])


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0016_centerdetail_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='quota_period_unit',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sms_quota_per_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='storage_patient_report_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='storage_server_report_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubscriptionBillingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_options', to='center_detail.subscriptionplan')),
            ],
            options={
                'ordering': ['plan__name', 'duration_days', 'name'],
            },
        ),
        migrations.AddField(
            model_name='centerdetail',
            name='billing_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='center_detail.subscriptionbillingoption'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionbillingoption',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='billing_option_discount_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionbillingoption',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='billing_option_duration_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionbillingoption',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='billing_option_base_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionbillingoption',
            constraint=models.UniqueConstraint(fields=('plan', 'name'), name='unique_billing_option_name_per_plan'),
        ),
        migrations.RunPython(
            seed_billing_options_and_assign_centers,
            migrations.RunPython.noop,
        ),
    ]
