# Generated by Django 5.2.12 on 2026-04-09 18:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


def migrate_to_active_subscription_schema(apps, schema_editor):
    SubscriptionPlan = apps.get_model('center_detail', 'SubscriptionPlan')
    CenterDetail = apps.get_model('center_detail', 'CenterDetail')
    ActiveSubscription = apps.get_model('center_detail', 'ActiveSubscription')

    free_plan, _ = SubscriptionPlan.objects.get_or_create(
        name='FREE',
        defaults={
            'duration_days': 30,
            'is_custom': False,
            'sms_quota': 0,
            'server_report_storage_quota_mb': 0,
            'patient_report_storage_quota_mb': 0,
        },
    )

    for plan in SubscriptionPlan.objects.all():
        sms_quota = getattr(plan, 'sms_quota_per_period', 0) or 0
        if sms_quota == 0:
            sms_quota = (
                getattr(plan, 'monthly_sms_quota', 0)
                or getattr(plan, 'bulk_sms_quota', 0)
                or 0
            )

        plan.sms_quota = sms_quota
        plan.server_report_storage_quota_mb = getattr(plan, 'storage_server_report_mb', 0) or 0
        plan.patient_report_storage_quota_mb = getattr(plan, 'storage_patient_report_mb', 0) or 0
        plan.save(
            update_fields=[
                'sms_quota',
                'server_report_storage_quota_mb',
                'patient_report_storage_quota_mb',
            ]
        )

    for center in CenterDetail.objects.all():
        plan = getattr(center, 'subscription_plan', None) or free_plan
        activated_on = getattr(center, 'plan_activated_on', None) or datetime.date.today()
        expires_on = activated_on + datetime.timedelta(days=plan.duration_days)

        ActiveSubscription.objects.update_or_create(
            center_detail=center,
            defaults={
                'subscription_plan': plan,
                'plan_activated_on': activated_on,
                'plan_expires_on': expires_on,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0017_subscriptionplan_quota_period_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='patient_report_storage_quota_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='server_report_storage_quota_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sms_quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ActiveSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_activated_on', models.DateField(default=datetime.date.today)),
                ('plan_expires_on', models.DateField()),
                ('center_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscription', to='center_detail.centerdetail')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_subscriptions', to='center_detail.subscriptionplan')),
            ],
            options={
                'ordering': ['-plan_expires_on', '-id'],
            },
        ),
        migrations.RunPython(migrate_to_active_subscription_schema, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='centerdetail',
            name='billing_option',
        ),
        migrations.RemoveField(
            model_name='centerdetail',
            name='plan_activated_on',
        ),
        migrations.RemoveField(
            model_name='centerdetail',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='bulk_price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='bulk_sms_quota',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='monthly_sms_quota',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price_monthly',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='quota_period_unit',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='sms_quota_per_period',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='storage_patient_report_mb',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='storage_server_report_mb',
        ),
        migrations.DeleteModel(
            name='SubscriptionBillingOption',
        ),
    ]
