# Generated by Django 5.2.12 on 2026-04-09 18:20

import center_detail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0018_remove_centerdetail_billing_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=models.SET(center_detail.models.get_free_plan), related_name='active_subscriptions', to='center_detail.subscriptionplan'),
        ),
    ]
