# Generated by Django 5.2.12 on 2026-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0021_alter_activesubscription_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
