# Generated by Django 5.2.12 on 2026-04-09 18:59

from django.db import migrations, models


def assign_plan_indices(apps, schema_editor):
    SubscriptionPlan = apps.get_model("center_detail", "SubscriptionPlan")

    free_plan = SubscriptionPlan.objects.filter(name__iexact="FREE").first()
    if free_plan:
        SubscriptionPlan.objects.filter(pk=free_plan.pk).update(plan_index=0)

    standard_plans = list(
        SubscriptionPlan.objects.exclude(name__iexact="FREE")
        .exclude(is_custom=True)
        .order_by("duration_days", "price", "name", "id")
    )
    custom_plans = list(
        SubscriptionPlan.objects.filter(is_custom=True).order_by(
            "duration_days", "price", "name", "id"
        )
    )

    next_index = 1
    for plan in standard_plans:
        SubscriptionPlan.objects.filter(pk=plan.pk).update(plan_index=next_index)
        next_index += 1

    for plan in custom_plans:
        SubscriptionPlan.objects.filter(pk=plan.pk).update(plan_index=next_index)
        next_index += 1


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0022_subscriptionplan_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['plan_index', 'name']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(assign_plan_indices, migrations.RunPython.noop),
    ]
