# Generated by Django 5.2.12 on 2026-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0023_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_index',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
