# Generated by Django 5.2.12 on 2026-05-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_detail', '0024_alter_subscriptionplan_plan_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_subscriptions', to='center_detail.subscriptionplan'),
        ),
    ]
